site_name: Duik API
site_url: http://duik.rxlab.io
repo_url: https://github.com/RxLaboratory/Duik_API/
edit_uri: tree/master/src/docs/
site_description: The Duik API comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2021-2022 <a href="https://rxlaboratory.org" target="_blank">Rainbox Laboratory</a> and <a href="http://duduf.com" target="_blank">Nicolas Dufresne</a>'
use_directory_urls: false
theme:
    name: null
    custom_dir: 'cinder'
    colorscheme: zenburn
extra:
    collapse_toc: true
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - fenced_code
    - toc
    - attr_list
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
    - collapser.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
nav:
    - v17.0.0-Alpha: index.md
    - Introduction: introduction.md
    - API Reference: reference/index.html
    - ...:
        #- Changelog: changelog.md
        #- Credits: credits.md
        - Contact: http://contact.rxlab.info
        - Chat: http://chat.rxlab.info
        - QuickTips: http://quicktips.rxlab.info
        - Tutorials: http://tuts.rxlab.info
        - Donate: http://donate.rxlab.info
        - License:
            - Introduction: license.md
            - Duik API license: gnu-gpl.md
            - Graphics license: https://creativecommons.org/licenses/by-nc-sa/4.0/
            - Documentation license: gnu-fdl.md
